POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVsdHN1YmFiZSIsImlkIjoiNjFiYjM3ZGRiMTljMWIwYzJlNGI2MjZmIiwiaWF0IjoxNjQwNTQ0ODQ3fQ.i1UphHWnpt2wFKUmqvxvPilf26aYfYozBCbx558rEW0

{
   "author" : "Tokendude",
   "title" : "Christmas coding pt 2", 
   "url" : "https://www.facebook.com/",
   "likes" : 7
}